"""initial migration

Revision ID: 2014e552907a
Revises: 
Create Date: 2020-08-26 14:07:23.676964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2014e552907a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_category', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_categories_id'), 'address_categories', ['id'], unique=False)
    op.create_table('class_of_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_of_activity', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_of_activities_id'), 'class_of_activities', ['id'], unique=False)
    op.create_table('constitution_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('constitution_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constitution_types_id'), 'constitution_types', ['id'], unique=False)
    op.create_table('enquiry_purposes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enquiry_purpose', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enquiry_purposes_id'), 'enquiry_purposes', ['id'], unique=False)
    op.create_table('enquiry_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enquiry_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enquiry_types_id'), 'enquiry_types', ['id'], unique=False)
    op.create_table('purposes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purposes_id'), 'purposes', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_states_id'), 'states', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('commercial_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_of_unit', sa.String(length=50), nullable=True),
    sa.Column('constitution_type', sa.String(length=50), nullable=True),
    sa.Column('class_of_activity', sa.String(length=50), nullable=True),
    sa.Column('pan_no', sa.String(length=10), nullable=True),
    sa.Column('reg_office_address', sa.Text(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=20), nullable=True),
    sa.Column('pin_code', sa.Integer(), nullable=True),
    sa.Column('enquiry_purpose', sa.String(length=50), nullable=True),
    sa.Column('member_ref_no', sa.Integer(), nullable=True),
    sa.Column('loan_amount', sa.Integer(), nullable=True),
    sa.Column('enquiry_type', sa.String(length=50), nullable=True),
    sa.Column('request_date', sa.Date(), nullable=True),
    sa.Column('request_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('remark', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_requests_id'), 'commercial_requests', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_requests_member_ref_no'), 'commercial_requests', ['member_ref_no'], unique=False)
    op.create_index(op.f('ix_commercial_requests_request_date'), 'commercial_requests', ['request_date'], unique=False)
    op.create_index(op.f('ix_commercial_requests_request_time'), 'commercial_requests', ['request_time'], unique=False)
    op.create_index(op.f('ix_commercial_requests_status'), 'commercial_requests', ['status'], unique=False)
    op.create_table('consumer_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_amount', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=6), nullable=True),
    sa.Column('pan_no', sa.String(length=10), nullable=True),
    sa.Column('aadhaar_no', sa.String(length=12), nullable=True),
    sa.Column('voter_id', sa.String(length=10), nullable=True),
    sa.Column('passport', sa.String(length=50), nullable=True),
    sa.Column('driving_license_no', sa.String(length=15), nullable=True),
    sa.Column('address', sa.Text(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('pin_code', sa.Integer(), nullable=True),
    sa.Column('address_category', sa.String(length=50), nullable=True),
    sa.Column('request_date', sa.Date(), nullable=True),
    sa.Column('request_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('remark', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumer_requests_id'), 'consumer_requests', ['id'], unique=False)
    op.create_index(op.f('ix_consumer_requests_name'), 'consumer_requests', ['name'], unique=False)
    op.create_index(op.f('ix_consumer_requests_request_date'), 'consumer_requests', ['request_date'], unique=False)
    op.create_index(op.f('ix_consumer_requests_request_time'), 'consumer_requests', ['request_time'], unique=False)
    op.create_index(op.f('ix_consumer_requests_status'), 'consumer_requests', ['status'], unique=False)
    op.create_table('commercial_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploaded_file', sa.String(length=255), nullable=True),
    sa.Column('uploaded_time', sa.DateTime(), nullable=True),
    sa.Column('commercial_request_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commercial_request_id'], ['commercial_requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commercial_request_id')
    )
    op.create_index(op.f('ix_commercial_reports_id'), 'commercial_reports', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_reports_uploaded_file'), 'commercial_reports', ['uploaded_file'], unique=True)
    op.create_table('consumer_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploaded_file', sa.String(length=255), nullable=True),
    sa.Column('uploaded_time', sa.DateTime(), nullable=True),
    sa.Column('consumer_request_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['consumer_request_id'], ['consumer_requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumer_reports_consumer_request_id'), 'consumer_reports', ['consumer_request_id'], unique=True)
    op.create_index(op.f('ix_consumer_reports_id'), 'consumer_reports', ['id'], unique=False)
    op.create_index(op.f('ix_consumer_reports_uploaded_file'), 'consumer_reports', ['uploaded_file'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consumer_reports_uploaded_file'), table_name='consumer_reports')
    op.drop_index(op.f('ix_consumer_reports_id'), table_name='consumer_reports')
    op.drop_index(op.f('ix_consumer_reports_consumer_request_id'), table_name='consumer_reports')
    op.drop_table('consumer_reports')
    op.drop_index(op.f('ix_commercial_reports_uploaded_file'), table_name='commercial_reports')
    op.drop_index(op.f('ix_commercial_reports_id'), table_name='commercial_reports')
    op.drop_table('commercial_reports')
    op.drop_index(op.f('ix_consumer_requests_status'), table_name='consumer_requests')
    op.drop_index(op.f('ix_consumer_requests_request_time'), table_name='consumer_requests')
    op.drop_index(op.f('ix_consumer_requests_request_date'), table_name='consumer_requests')
    op.drop_index(op.f('ix_consumer_requests_name'), table_name='consumer_requests')
    op.drop_index(op.f('ix_consumer_requests_id'), table_name='consumer_requests')
    op.drop_table('consumer_requests')
    op.drop_index(op.f('ix_commercial_requests_status'), table_name='commercial_requests')
    op.drop_index(op.f('ix_commercial_requests_request_time'), table_name='commercial_requests')
    op.drop_index(op.f('ix_commercial_requests_request_date'), table_name='commercial_requests')
    op.drop_index(op.f('ix_commercial_requests_member_ref_no'), table_name='commercial_requests')
    op.drop_index(op.f('ix_commercial_requests_id'), table_name='commercial_requests')
    op.drop_table('commercial_requests')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_states_id'), table_name='states')
    op.drop_table('states')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_purposes_id'), table_name='purposes')
    op.drop_table('purposes')
    op.drop_index(op.f('ix_enquiry_types_id'), table_name='enquiry_types')
    op.drop_table('enquiry_types')
    op.drop_index(op.f('ix_enquiry_purposes_id'), table_name='enquiry_purposes')
    op.drop_table('enquiry_purposes')
    op.drop_index(op.f('ix_constitution_types_id'), table_name='constitution_types')
    op.drop_table('constitution_types')
    op.drop_index(op.f('ix_class_of_activities_id'), table_name='class_of_activities')
    op.drop_table('class_of_activities')
    op.drop_index(op.f('ix_address_categories_id'), table_name='address_categories')
    op.drop_table('address_categories')
    # ### end Alembic commands ###
